secret=${SPRING_SECRET_DEMO}
env.var1=${SPRING_ENV_VAR_1}
env.var2=${SPRING_ENV_VAR_2}
PLATFORM: US_PLATFORM_1
API_SERVER:https://qualysapi.qualys.com
QUALYS_USERNAME: quays_pg19
QUALYS_PASSWORD: o34kLasNpg
USE_PROXY: false
PROXY_SERVER: null
PROXY_PORT:0
PROXY_USERNAME:null
PROXY_PASSWORD:null
WEBAPP_ID: 1069358967
SCAN_NAME: New WAS Vulnerability Scan launched from API
SCAN_TYPE: VULNERABILITY
AUTH_RECORD: other
AUTH_RECORD_ID: 2047697
OPTION_PROFILE: use default
OPTION_PROFILE_ID: null
CANCEL_OPTION: none
CANCEL_HOURS: null
SEVERITY_ONE_LIMIT:0
SEVERITY_TWO_LIMIT:0
SEVERITY_THREE_LIMIT:0
SEVERITY_FOUR_LIMIT:0
SEVERITY_FIVE_LIMIT:0
IS_SEVERITY_ONE: false
IS_SEVERITY_TWO: false
IS_SEVERITY_THREE: true
IS_SEVERITY_FOUR: false
IS_SEVERITY_FIVE: false
IS_FAIL_ON_QID_FOUND: false
QID_LIST: null 
FAIL_ON_SCAN_ERROR:false